### ISSUE TITLE
Describe configuration options

### ISSUE THREAD

**Issue by dmolineus** [phpcq/phpcq#17]
The `ConfigurationPluginInterface` should provide a method where configuration are described for help commands and/or for building a default configuration

**Comment by dmolineus** [comment]
We want to use a `ConfigOptionsBuilderInterface` which is part of the `ConfigurationPluginInterface`

```php
public function describeConfigOption(ConfigOptionsBuilderInterface $builder) : void
{
    $builder->describeOption('name', 'array', 'A list of file names to check [default: ["*.php"]].');
}
```

**Comment by discordier** [comment]
Should the default value be added as optional last argument? This would kill any type hint on the default value argument.

We could also provide describe options per type:
```php
$builder->describeArrayOption('name', 'A list of file names to check.', ['*.php']);
$builder->describeIntOption('log-level', 'The log level.', 1);
$builder->describeStringOption('output-file', 'Output-file.', 'my.log');
```

**Comment by dmolineus** [comment]
I started to develop this feature in 8e7122871054daa5eacc5bdb79a471fdcf8768d4. I added some comments in the commit on github.

**Comment by discordier** [comment]
I think it would make sense to open a WIP PR for this then, as it is more easy to discuss in a PR than in a commit.
I did almost miss the commit comments.
