### ISSUE TITLE
Phing instead of Ant?

### ISSUE THREAD

**Issue by tristanlins** [phpcq/phpcq#2]
[Phing](http://www.phing.info/) is mostly compatible with the ant `build.xml` files. Expect that you can write custom tasks in PHP.
See http://www.phing.info/docs/guide/stable/ch06s06.html

This would make it easier for us, to integrate checks like the https://github.com/contao-community-alliance/build-system-tool-branch-alias-validation directly into the build system as build task.

``` xml
<project name="example" default="validate">
    <includepath classpath="vendor/contao-community-alliance/build-system/src" />
    <taskdef name="composer-validate-branch-alias" classname="ComposerValidateBranchAliasTask" />

    <target name="validate">
      <composer-validate-branch-alias[ file="composer.json"][ ignore="feature/*"] />
    </target>
</project>
```

**Comment by dmolineus** [comment]
We're working on a new 2.0 release with an own task runner.
