### ISSUE TITLE
Local tool support

### ISSUE THREAD

**Issue by dmolineus** [phpcq/phpcq#30]
The current dev-2.0 does not have the local tool support

**Comment by discordier** [comment]
It appears you are working on it at the moment in https://github.com/phpcq/gnupg/commit/3b39d98a644a660d9b504ab571082f4391e47ad4?

**Comment by dmolineus** [comment]
Providing a local/plugin should work if we ship a repository.json. This is a small overhead but works quite well. Maybe we integrate the approach of an inline repository as started here https://github.com/phpcq/phpcq/tree/feature/repository-types.

So I guess we can close it for now.
