### ISSUE TITLE
Unified log format

### ISSUE THREAD

**Issue by dmolineus** [phpcq/phpcq#31]

**Comment by dmolineus** [comment]
I recently stumpled upon [checkstyle](https://github.com/checkstyle/checkstyle) which could maybe fit our needs to have a unified log format. Checkstyle is a tool from the Java world, but the output format is supported by several PHP tools. The output format is an xml format, specified [here]:(https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/checkstyle.xsd)

## Tools

* PHPCQ should output all logs combined as a checkstyle formatted file
* PHPCQ may force tools to generate checkstyle xml reports and parses it later on.

## Tool support
Right know following tools already support checkstyle:

### Supported

- [x] psalm, `--report=checkstyle.xml` or `--output-format=checkstyle`
- [x] phpcs, `--report=checkstyle`

### Not supported

- [  ] phpunit, but own xml format
- [  ] phpmd, but own xml format
- [  ] phpcpd, but own xml format
- [  ] phploc, but own xml format. Probably won't fit into checkstyle format
- [  ] phpcbf
- [  ] composer-require-checker
- [  ] composer-normalize, probably won't fit into checkstyle format (produces a diff view optionally)

### Supported but not integrated into phpcq yet

- [x] PHP Coding Standards Fixer
- [x] PHPStan

## Benefits

- [ ] IDE support (?)
- [x] Annotations for Github Checks API, https://github.com/staabm/annotate-pull-request-from-checkstyle

**Comment by dmolineus** [comment]
Some ongoing thoughts:

1. We probably can't force all tools to a file, line specific report format
2. Using a file, line specific report format where it fits will be an improvement, we should take the step
3. We need a report format which supports both
4. Using checkstyle for it seems reasonable as some tools already support it
5. So I vote for an extended output format, based on checkstyle
6. If a tool does not support `checkstyle` we might parse the output and create the checkstyle for it
7. Parsing the report might bloat the plugins. Maybe we have to ship some parsers as part of phpcq as well

## Report format

Our report format might 

 - General information (phpcq version, tools etc.)
 - Raw output of tools not supporting `checkstyle`
 - `checkstyle` for file/line specific errors

## Implementation

### TaskRunnerBuilderInterface

Our task runner should know the generated output format. By default it's `raw`. A tool might tell it's specific format, e.g. `phpunit`. PHPCQ may decide to parse it and convert it to `checkstyle` or handle it as raw.

```diff
interface TaskRunnerBuilderInterface
{
+ public function withCheckstyleOutput(): TaskRunnerBuilderInterface;
+ public function withOutputFormat(string $format): TaskRunnerBuilderInterface;
}
```

Question: Maybe we need to parse report files also and not only trusting on console output?

### Output format plugins

We maybe also allow plugins to register it's own parsers which parses a named output to checkstyle format.

```php

interface OutputFormatParserPluginInterface
{
    /** @return array<string, OutputFormatParserInterface> **/
    public function outputFormatParsers() : iterable
}

interface OutputFormatParserInterface
{
    /** Parses output and returns it as string **/
    public function parse(string $output) : string;
}

@discordier Wdyt?

**Comment by discordier** [comment]
> Some ongoing thoughts:
> 
> 1. We probably can't force all tools to a file, line specific report format

For this case, I'd vote to mark an issue for `File xyz.ext, Line 1` as already done by phpmd et al.

> 2. Using a file, line specific report format where it fits will be an improvement, we should take the step

Agreed

> 3. We need a report format which supports both
> 4. Using checkstyle for it seems reasonable as some tools already support it

Checkstyle is fine for me and widely supported.

> 5. So I vote for an extended output format, based on checkstyle

Agreed.

> 6. If a tool does not support `checkstyle` we might parse the output and create the checkstyle for it
> 7. Parsing the report might bloat the plugins. Maybe we have to ship some parsers as part of phpcq as well

Would need scrubbing log files as well as console output. Therefore we will need some transformer plugin infrastructure. I am with you on that one.

> ## Report format
> Our report format might
> 
> * General information (phpcq version, tools etc.)
> * Raw output of tools not supporting `checkstyle`
> * `checkstyle` for file/line specific errors

For transforming `checkstyle.xml` reports, there are [various xsl files](https://github.com/checkstyle/contribution/tree/master/xsl). We could use these as well.

> ## Implementation
> ### TaskRunnerBuilderInterface
> Our task runner should know the generated output format. By default it's `raw`. A tool might tell it's specific format, e.g. `phpunit`. PHPCQ may decide to parse it and convert it to `checkstyle` or handle it as raw.
> 
> ```diff
> interface TaskRunnerBuilderInterface
> {
> + public function withCheckstyleOutput(): TaskRunnerBuilderInterface;
> + public function withOutputFormat(string $format): TaskRunnerBuilderInterface;
> }
> ```
> 
> Question: Maybe we need to parse report files also and not only trusting on console output?

This is my main concern, most tool output I know are better handled via a log file.
Parsing these files would be better instead.
The build output would be way too polluted when being written to stdout as well (xml on a terminal is too noisy).

We therefore might want to have post processing plugins (a `LogTransformerBuilderInterface` or the like).

> ### Output format plugins
> We maybe also allow plugins to register it's own parsers which parses a named output to checkstyle format.
> 
> ```
> interface OutputFormatParserPluginInterface
> {
>     /** @return array<string, OutputFormatParserInterface> **/
>     public function outputFormatParsers() : iterable
> }
> 
> interface OutputFormatParserInterface
> {
>     /** Parses output and returns it as string **/
>     public function parse(string $output) : string;
> }
> ```

Question hereto, how to handle tools that spit out multiple log files? Namely phploc, which is able to produce an xml dump and an svg file along side. This would need at least two different parsers.
How to tie the `SVGParser` to the svg file and how to tie the `XMLTransformer` to the xml file?
