### ISSUE TITLE
Define tool configuration handling

### ISSUE THREAD

**Issue by dmolineus** [phpcq/phpcq#42]
I'd like to define and document how the tool configuration is handled. 

## Extending config
Right now, it's possible to define tool configurations on several levels:

- Global configuration at `tool-config`
- Directory base configuration at `tool-config.directories.directory`
- Chain specific tool configuration

There are different rules handling merging:
- Directory config extends tool-config
- Chain config replaces tool-config

Extending config makes a lot of sense, but there's no way to decide when to extend and then to override. That's why I propose to drop the the extending when processing the configuration at all. As we use magic yaml, the user can use yaml anchors to merge and extend configuration if required.

The default behaviour would be then:
- phpcq checks if a chain configuration exists
- If available it uses the configuration
- If not the global tool config is used

## Directory specific configuration
I like also to discuss how to deal directory specific configuration. For my understanding where are two scenarios:

1. A Directory has no configuration, The directory is processed by the global/chain config based task
2. A directory has a custom configuration: The directory is processed by a separate task
3. As a result a task will always get directories as a list of paths and does not have to deal with possible directory configuration. Phpcq will consider it and maybe call the `processConfig` method multiple times with the preprocessed configuration.

I already implemented phpcpd this way, see https://github.com/phpcq/repository/blob/d0c3a96031f51d38b2beffdf7d18909d8791f594/bootstrap/plugins/phpcpd/phpcpd-all.php#L79-L154

**Comment by discordier** [comment]
@dmolineus can we close this? IMO we are done with the tool config now?
