### ISSUE TITLE
Disable xdebug globally and allow task to enable it selectively

### ISSUE THREAD

**Issue by discordier** [phpcq/phpcq#46]
We should, for performance reasons, disable `xdebug` via custom ini file and pass this ini file to all phar running processes.
As some tools (phpunit) might need xdebug, we would also need to add some `TaskBuilderInterface::allowXDebug()` for phar tasks (which would then be a custom task builder interface as this option does not make sense for non phar builders).

**Comment by dmolineus** [comment]
It makes also sense for php processes, so we might want to add a factory method for php processes as well.

**Comment by discordier** [comment]
Currently there was no need for it but why not.

**Comment by dmolineus** [comment]
If we provide support for `phpspec` we will as working with the unprefixed phar which also includes the project autoload file causes more issues than using a phar would solve.

**Comment by discordier** [comment]
I decided to go the other way around and let plugins disable xdebug.

See: https://github.com/phpcq/plugin-api/pull/14, https://github.com/phpcq/phpcq/pull/53
