### ISSUE TITLE
Make a PR on all repositories still using contao-community-alliance/build-system

### ISSUE THREAD

**Issue by tristanlins** [phpcq/phpcq#6]
- [ ] [bit3/contao-ikimea-browser-service develop](https://github.com/bit3/contao-ikimea-browser-service/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [bit3/contao-ikimea-browser-service master](https://github.com/bit3/contao-ikimea-browser-service/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [bit3/contao-logger develop](https://github.com/bit3/contao-logger/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0@dev
- [ ] [bit3/contao-logger master](https://github.com/bit3/contao-logger/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0@dev
- [ ] [bit3/contao-mobile-detect-service develop](https://github.com/bit3/contao-mobile-detect-service/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [bit3/contao-mobile-detect-service master](https://github.com/bit3/contao-mobile-detect-service/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [bit3/string-builder develop](https://github.com/bit3/string-builder/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [bit3/string-builder master](https://github.com/bit3/string-builder/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/backports-initialize-system develop](https://github.com/contao-community-alliance/backports-initialize-system/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/composer-client develop](https://github.com/contao-community-alliance/composer-client/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/composer-plugin develop](https://github.com/contao-community-alliance/composer-plugin/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/composer-plugin master](https://github.com/contao-community-alliance/composer-plugin/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/dependency-container develop](https://github.com/contao-community-alliance/dependency-container/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/dependency-container master](https://github.com/contao-community-alliance/dependency-container/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/event-dispatcher develop](https://github.com/contao-community-alliance/event-dispatcher/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/event-dispatcher master](https://github.com/contao-community-alliance/event-dispatcher/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [contao-community-alliance/usage-statistic-client develop](https://github.com/contao-community-alliance/usage-statistic-client/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [contao-community-alliance/usage-statistic-client develop](https://github.com/contao-community-alliance/usage-statistic-client/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [contao-community-alliance/vcs-synchronizer develop](https://github.com/contao-community-alliance/vcs-synchronizer/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/url-builder develop](https://github.com/contao-community-alliance/url-builder/tree/develop)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [contao-community-alliance/url-builder master](https://github.com/contao-community-alliance/url-builder/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [cyberspectrum/contao-debugger master](https://github.com/cyberspectrum/contao-debugger/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_geoprotection tng](https://github.com/metamodels/attribute_geoprotection/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_translatedtext tng](https://github.com/metamodels/attribute_translatedtext/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_translatedurl tng](https://github.com/metamodels/attribute_translatedurl/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_url tng](https://github.com/metamodels/attribute_url/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_alias tng](https://github.com/metamodels/attribute_alias/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [metamodels/attribute_checkbox tng](https://github.com/metamodels/attribute_checkbox/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_color tng](https://github.com/metamodels/attribute_color/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_decimal tng](https://github.com/metamodels/attribute_decimal/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_langcode tng](https://github.com/metamodels/attribute_langcode/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_numeric tng](https://github.com/metamodels/attribute_numeric/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_translatedfile tng](https://github.com/metamodels/attribute_translatedfile/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/attribute_translatedtags tng](https://github.com/metamodels/attribute_translatedtags/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/filter_checkbox tng](https://github.com/metamodels/filter_checkbox/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/filter_fromto tng](https://github.com/metamodels/filter_fromto/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/phpunit-contao-database master](https://github.com/metamodels/phpunit-contao-database/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/base-unit-tests master](https://github.com/metamodels/base-unit-tests/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/core searchable_pages](https://github.com/metamodels/core/tree/searchable_pages)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/filter_select tng](https://github.com/metamodels/filter_select/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/filter_tags tng](https://github.com/metamodels/filter_tags/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [x] [metamodels/filter_text tng](https://github.com/metamodels/filter_text/tree/tng)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [cboelter/metamodels-filter_condition_membergroup master](https://github.com/cboelter/metamodels-filter_condition_membergroup/tree/master)<br>
    require-dev contao-community-alliance/build-system ~1.0
- [ ] [contao-bootstrap/grid-editor develop](https://github.com/contao-bootstrap/grid-editor/tree/develop)<br>
    require-dev contao-community-alliance/build-system 1.0.x-dev
- [ ] [contao-bootstrap/grid-editor master](https://github.com/contao-bootstrap/grid-editor/tree/master)<br>
    require-dev contao-community-alliance/build-system 1.0.x-dev

**Comment by discordier** [comment]
Closing, I guess in 2018 no one is really still using the cca build system. :D
